[General]
bypass-system = false
compatibility-mode = 3
tun-excluded-routes = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32,239.255.255.250/32
hijack-dns = *:53
dns-direct-system = false
dns-direct-fallback-proxy = false
private-ip-answer = true
always-ip-address = true
dns-server = https://8.8.8.8/dns-query#proxy=personal-server&ecs=77.88.0.0/18&ecs-override=true,https://8.8.4.4/dns-query#proxy=personal-server&ecs=77.88.0.0/18&ecs-override=true
fallback-dns-server = https://8.8.8.8/dns-query#proxy=personal-server&ecs=77.88.0.0/18&ecs-override=true,https://8.8.4.4/dns-query#proxy=personal-server&ecs=77.88.0.0/18&ecs-override=true
proxy-dns-server = https://77.88.8.8/dns-query
ipv6 = false
prefer-ipv6 = false
udp-policy-not-supported-behaviour = REJECT
block-quic = all
icmp-auto-reply = false
always-reject-url-rewrite = false

[Rule]
DOMAIN-KEYWORD,yandex,DIRECT
DOMAIN-KEYWORD,ozon,DIRECT
DOMAIN-KEYWORD,sberbank,DIRECT
DOMAIN-KEYWORD,tbank,DIRECT
DOMAIN,yastatic.net,DIRECT
GEOIP,RU,DIRECT
FINAL,PROXY

[Host]
# Укажите айпи сервера для его домена, чтобы убрать зависимость от DNS (при условии, что айпи сервера не меняется часто)
# server-domain.com = <server-ip>

# Apple сервисы используют DNS без ECS для правильного определения айпи CDN, поскольку весь трафик устройства уходит в прокси
*.apple.com = server:https://8.8.8.8/dns-query#proxy=personal-server
*.apple-dns.net = server:https://8.8.8.8/dns-query#proxy=personal-server
*.icloud.com = server:https://8.8.8.8/dns-query#proxy=personal-server
*.itunes.apple.com = server:https://8.8.8.8/dns-query#proxy=personal-server
*.apps.apple.com = server:https://8.8.8.8/dns-query#proxy=personal-server
*.mzstatic.com = server:https://8.8.8.8/dns-query#proxy=personal-server
*.com.akadns.net = server:https://8.8.8.8/dns-query#proxy=personal-server
*.g.aaplimg.com = server:https://8.8.8.8/dns-query#proxy=personal-server
*.dscx.akamaiedge.net = server:https://8.8.8.8/dns-query#proxy=personal-server
*.dsce9.akamaiedge.net = server:https://8.8.8.8/dns-query#proxy=personal-server
itunes.apple.com.edgekey.net = server:https://8.8.8.8/dns-query#proxy=personal-server
apps.itunes-nocookie.com = server:https://8.8.8.8/dns-query#proxy=personal-server
h3.media.apple.map.fastly.net = server:https://8.8.8.8/dns-query#proxy=personal-server